# -*- coding: utf-8 -*-
"""(21.5.18)hw-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sULuYlU2TXAL3dlH-l8Rk4uU2I_W37kk
"""

np3 = np.arange(10, 241, 10)

np3

np33 = np3.reshape(2, 12)

np33

np333 = np33.reshape(2, 3, 4)

np333.shape

np333

np333[0][0][2]

np333[0][2]

np333[1:, 1:, :2]

np64 = np333.reshape(6, 4)

np64

np64[1:5, 2:]