# -*- coding: utf-8 -*-
"""(21.5.18)hw-1.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L7ZPXXF0Tnq6bDoyXD-TbO-98jfqSJzr

▶ 5월18일 도전 과제

1) 구구단을 2차원 배열로 만드시오. gdan
2) int16으로 자료형을 변경하시오.
 
3) 3단에만 50을 더하시오.
4) 5단에만 100을 곱하시오.
5) 모양을 어떤 형태든 다르게 변경하시오.
"""

dan = np.array([i for i in range(1, 10)])

dan

g = [i * dan for i in range(1, 10)]

g

gdan = np.array([i * dan for i in range(1, 10)], dtype = np.int16)

gdan

gdan[2] + 50

gdan[4] * 100

gdan.reshape(1, 81)
